### ISSUE TITLE
add icon for external links to link component

### ISSUE THREAD

**Issue by karlbaumhauer** [PurposeDevelopment/bnb-frontend#121]
@tilmansch hier brauchen wir dann irgendwann mal ein Logo für

**Comment by tilmansch** [comment]
was ist hier gemeint? Screenshot?

**Comment by karlbaumhauer** [comment]
@tilmansch https://www.google.com/search?safe=active&rls=en&q=external+link+svg&tbm=isch&source=univ&client=safari&sa=X&ved=2ahUKEwi4r9_5wvnnAhUlxoUKHfWAAxUQsAR6BAgKEAE&biw=1680&bih=939
