### ISSUE TITLE
Aktiv werden: Nominiere die besten Kandidaten - Link entfernen

### ISSUE THREAD

**Issue by AlisaSophie** [PurposeDevelopment/bnb-frontend#124]
Im Unterpunkt "Nominiere die besten Kandidaten" unter Aktiv werden bitte noch nicht aufs Formular verlinken, da dieses erst ab 12.03. möglich ist. Lösungsvorschlag: "Nominiere hier ab 12.02. deine*n Kandidat*in" statt Link

**Comment by karlbaumhauer** [comment]
duplicate #136
