### ISSUE TITLE
several text changes

### ISSUE THREAD

**Issue by karlbaumhauer** [PurposeDevelopment/bnb-frontend#136]
**Über uns:**
- [x] freiwillige * r (kleingeschrieben)
- [x] Helfer * in (gendern durchziehen)

**Home - BNB Prinzip**
- [x] Abstand nach der Überschrift im ersten Punkt an die anderen anpassen.

**Aktiv werden:**
- [x] Im Unterpunkt "Nominiere die besten Kandidaten" unter Aktiv werden bitte noch nicht aufs Formular verlinken, da dieses erst ab 12.03. möglich ist. Lösungsvorschlag: "Nominiere hier ab 12.02. deinen Kandidatin" statt Link

**Comment by karlbaumhauer** [comment]
@AlisaSophie @lauracasadevall 

hier könnt ihr in der Beschreibung einfach alle Textänderungen eintragen. Einfach nach dem oben gegebenen Schema.

**Comment by lauracasadevall** [comment]
**Allgemein:**
Du/Dich wird immer klein geschrieben, es sei ist am Anfang des Satzes oder nach Doppelpunkt. 

**Startseite/ Newsletter Formular**
- [ ] Emailadresse --> zu E-Mail
- [ ] AGB löschen aus Bestätigungsbox

**Kontaktseite (http://staging.brandnewbundestag.de/contact.html)**

- [ ] Email --> E-Mail
- [ ] Ihre Nachricht --> Deine Nachricht

**Comment by lauracasadevall** [comment]
Ich habe jetzt mal die Sachen gemacht, die ich für final halte auf Überuns gibts noch relativ viel DU/DICH fehler, die habe ich jetzt noch nicht gesammelt weil da ja noch texte kommen, oder @AlisaSophie ?

**Comment by karlbaumhauer** [comment]
ich hab mal glob alle Du/Dich in du/dich geändert. "Dein" hab ich keins gefunden...

**Comment by AlisaSophie** [comment]
Footer: Bitte "FAQ" statt "Häufige Fragen/FAQ"

**Comment by AlisaSophie** [comment]
Aktiv werden: Hier sind noch Platzhaltertexte für "Rück deinen Wahlkreis in den Fokus" und "spenden" fehlt ganz. Texte sind im Drive angelegt, brauchst du hier noch was von uns @karlbaumhauer ?

**Comment by AlisaSophie** [comment]
Impressum: 
Bitte Text noch einmal aktualisieren ausgehend von Drive-Dokument
Social Media-Profile: Facebook ist falsch geschrieben

**Comment by karlbaumhauer** [comment]
@AlisaSophie ich meine nun alle Fehler ausgebessert zu haben. Falls nicht, bitte explizit schreiben was falsch ist. Ich muss sonst immer alle Texte neu kopieren, was mega der Aufwand ist.
