### ISSUE TITLE
contact page text

### ISSUE THREAD

**Issue by karlbaumhauer** [PurposeDevelopment/bnb-frontend#138]
set contact page to normal text and remove contact form cause it won't be usable until 01.03.

**Comment by karlbaumhauer** [comment]
@AlisaSophie gibt es hier ein Text der auf der Seite stehen soll? sowas wie " falls du eine Frage hast..."

**Comment by AlisaSophie** [comment]
Textvorschlag: Jede Unterstützung zählt! Werde jetzt Teil unserer Bewegung und lass uns gemeinsam eine neue Generation mutiger Entscheidungsträger*innen suchen, unterstützen und in die Parlamente bringen. Trage dich dafür bitte in das Formular ein und gib gerne im Textfeld an, in welchem Bereich du uns unterstützen möchtest. Wir melden uns dann in den kommenden Tagen bei dir. Wir freuen uns auf dich!
