### ISSUE TITLE
SEO vor Launch: Kritische SEO To Dos

### ISSUE THREAD

**Issue by VickyW987** [PurposeDevelopment/bnb-frontend#150]
1. Einfügen meta-tag robots im <head>-Bereich
- [x] `<meta name="robots" content="index,follow" />`

2. Ändern meta-tags title und description im <head>-Bereich

- [x] Homepage:

`<title>Brand New Bundestag | Unabhängig & Überparteilich</title>
<meta name="description" content="Bring mit uns neue Politiker*innen ins Parlament. Wir kämpfen für gesellschaftlichen Fortschritt und eine gerechtere Zukunft. ► Sei dabei und unterstütze uns!">`

- [x] Aktiv werden:

`<title>Brand New Bundestag | Aktiv werden</title>
<meta name="description" content="Je mehr wir sind, desto mehr Gewicht haben wir. Unterstütze uns aktiv ehrenamtlich bei dir vor Ort oder als Botschafter*in für unsere Bewegung.">`

- [x] Über uns:

`<title>Brand New Bundestag | Über uns</title>
<meta name="description" content="Wir setzen uns für eine Politik für die breite Gesellschaft ein - für dich und mich! Für uns alle! ► Sei dabei und unterstütze uns!">`

- [x] Unsere Forderungen:

`<title>Brand New Bundestag | Unsere Forderungen</title>
<meta name="description" content="Unsere Forderungen für eine Gesellschaft, die demokratisch und inklusiv ausgerichtet ist, die nachhaltig denkt und dabei lokal wie global in Aktion tritt.">`

- [x] FAQ:

`<title>Brand New Bundestag | FAQs</title>
<meta name="description" content="Antworten auf die häufigsten Fragen zur Initiative Brand New Bundestag.">`

- [x] Kontakt:

`<title>Brand New Bundestag | Kontakt</title>
<meta name="description" content="Gemeinsam für gesellschaftlichen Fortschritt und eine gerechtere Zukunft. ► Kontaktiere uns!">`

- [x] Impressum:

`<title>Brand New Bundestag | Impressum</title>
<meta name="description" content="Gemeinsam für gesellschaftlichen Fortschritt und eine gerechtere Zukunft.">`

- [x] Datenschutz:

`<title>Brand New Bundestag | Datenschutz</title>
<meta name="description" content="Gemeinsam für gesellschaftlichen Fortschritt und eine gerechtere Zukunft.">`

3. Erstellen und Ablegen der sitemap.xml

- [x] sitemap.xml bitte im Hauptverzeichnis ablegen, sodass sie unter /sitemap.xml aufrufbar ist

4. Erstellen und Ablegen der robots.txt

- [x] robots.txt bitte mit folgendem Inhalt erstellen und im Hauptverzeichnis ablegen, sodass sie unter /robots.txt aufrufbar ist

- robots.txt:
User-agent: *
Disallow: /[admin bzw. login Bereich der Seite]/
Noindex: /[admin bzw. login Bereich der Seite]/
Disallow: /[falls vorhanden, eine thank-you Seite, z. B. nach der Newsletter-Anmeldung]
[Leerzeile]
Sitemap: https://www.brandnewbundestag.de/sitemap.xml
- falls keine dieser Seiten vorhanden ist, genügt Disallow:

5. Hinzufügen des https Zertifikats für Seite

- [x] Seite sollte am Ende über https aufgerufen werden können

**Comment by VickyW987** [comment]
Generelle Frage zum Pflegen der Seite:
Wird es einen Admin Bereich geben und kann man dort dann die meta tags und andere SEO Einstellungen selbst vornehmen?

**Comment by VickyW987** [comment]
@karlbaumhauer: Ich hoffe, die Beschreibung passt so. Wenn ich was anders machen kann, sag' gerne Bescheid! :)

**Comment by karlbaumhauer** [comment]
@VickyW987 

danke für die Infos. 1-3 werde ich mir morgen anschauen. Da hab ich auf Infos gewartet.

zu 4. müssen wir evtl. mal kurz sprechen. kann ich dich morgen anrufen? Wenn ja, schick mir mal bitte eine SMS auf 015776801711.

5. geht erst mit dem Go-Live da in dem Paket nur die Hauptdomain ein Zertifikat bekommen kann. Ist aber schon eingerichtet.

Einen Admin Bereich wird es nicht geben. Aus Zeitgründen ist die Seite vorerst statisches HTML. Irgendwann soll das dann mal kommen. Bis dahin, müssen die Änderungen über uns laufen oder Ihr habt am Ende jemanden, der/die sich mit Github und Coding auskennt. Dort können dann die Änderungen easy vorgenommen werden.

**Comment by karlbaumhauer** [comment]
@VickyW987 we are live...;-)
