### ISSUE TITLE
SEO nach Launch: im Idealfall vor Nominierungskampagne

### ISSUE THREAD

**Issue by VickyW987** [PurposeDevelopment/bnb-frontend#155]
1. Link-Bezeichnungen anpassen
Link-Bezeichnungen am besten in deutsche Bezeichnungen ändern
- [x] /get-started > /aktiv-werden
- [x] /about-us > /ueber-uns
- [x] /claims > /unsere-forderungen
- [x] /contact > /kontakt
- [x] /imprint > /impressum
- [x] /data-protection > /datenschutz

2. 404-Seite & 301- bzw. 302-Weiterleitungen
- [x] Standard-Einstellungen vornenehmen
- [x] ggf. je nach System für die Umbenennung der Links oben noch eine 302-Weiterleitung einrichten, manche Systeme machen das automatisch

3. meta-tags für Facebook und Twitter einrichten

- [x] Die Tags sind schon auf der Seite, müssen aber bitte noch einmal angepasst werden:

[Tags wurden hier nicht dargestellt, siehe Kommentar]
>> Beispiel für Homepage, bitte für die anderen Seiten ebenfalls einfügen, og:title und og:description können analog zu den meta-tags aus #150 übernommen werden, og:image und og:url bitte entsprechend auf die jeweilige Seite anpassen

4. generell: Ladezeiten möglichst kurz halten

- [ ] kann ich nach Launch noch einmal genauer prüfen und bessere Vorschläge machen, falls hier was auffällt

**Comment by VickyW987** [comment]
<meta property="og:title" content="Brand New Bundestag | Unabhängig & Überparteilich">
<meta property="og:description" content="Bring mit uns neue Politiker*innen ins Parlament - für gesellschaftlichen Fortschritt & eine gerechtere Zukunft. ► Sei dabei und unterstütze uns!">
<meta property="og:image" content="[Bild-URL des Hero-Images der Homepage]">
<meta property="og:url" content="https://www.brandnewbundestag.de">
<meta name="twitter:card" content="summary_large_image">

**Comment by karlbaumhauer** [comment]
@VickyW987 du kannst jetzt nochmal testen. Die Weiterleitungen hab ich noch nicht aber alle nötigen meta tags sollten nun drin sein. Vor allem bitt auf Social Media achten. Da ich z.b. Kein FB habe kann ich da nicht testen.

**Comment by VickyW987** [comment]
Hallo @karlbaumhauer,

Dankeschön! :)
Ich habe die Tags mit Tools von FB und Twitter geprüft. Dabei sind noch Themen aufgefallen, die von den Seiten nicht 100% erkannt werden.

- [ ] og:url wird aktuell auf brandnewbundestag.de inkl. /index.html angegeben. Wird als Weiterleitung erkannt, kann das nur in https://www.brandnewbundestag.de/ geändert werden?
- [ ] og:image wird aktuell als relativer Pfad angegeben, kann das in den ganzen Pfad geändert werden? Also in https://www.brandnewbundestag.de/_assets/img/sahreImage.png ?
- [ ] in der robots.txt bitte unter Disallow den / entfernen, hier einfach leer lassen

Der Rest sollte passen, soweit ich das gerade sehen kann. Ich teste aber auch gerne noch einmal im Anschluss.

**Comment by karlbaumhauer** [comment]
@VickyW987 ist alles soweit eingepflegt und geht später mit Textänderungen online. gerne dann nochmal neu testen.

Den og:url Tag hab ich nun wieder auf die Hauptdomain gesetzt. Ich hatte es vorher so angelegt, damit die Unterseiten dann auch eine entsprechende URL haben. Sollen alle Seiten dieselbe Adresse eingetragen haben? 

Damit hat sich vermutlich auch die Test-Anfrage an (@tilmansch und @AlisaSophie ) aus #208 erledigt.

**Comment by karlbaumhauer** [comment]
@VickyW987 ist nun alles hochgeladen. bitte nochmal prüfen.

**Comment by VickyW987** [comment]
Hallo @karlbaumhauer,

sieht so weit alles gut aus, danke dir! :) 

Du hast recht, es ist besser, wenn die Unterseiten auch die entsprechende URL haben und die Seiten nicht alle dieselbe Adresse haben.

Gibt es eine Möglichkeit, die URLs trotzdem unterschiedlich anzugeben, ohne dass /index.html eingetragen werden muss? Oder geht nur entweder oder? Wenn es nicht anders geht, dann lieber die unterschiedlichen URLs. :) Ich hoffe, das ist nicht zu viel Arbeit! Dankeschön!

Aktuell sieht es so aus:
![Bildschirmfoto 2020-03-22 um 14 19 53](https://user-images.githubusercontent.com/61582734/77250737-2b6a7c00-6c4a-11ea-8908-16bcdb95fabf.png)

Also alles cool und schick!
LG
Vicky

**Comment by karlbaumhauer** [comment]
@VickyW987 die Domains hab ich nun für die Unterseiten wieder eingestellt. Für die Hauptseite steht allerdings nur noch www.brandnewbundestag.de und kein direkter Link zur index.html Seite mehr. sollte also passen (hoffentlich)...;-)

Wenn dann alles soweit ok ist, kannst Du das Ticket gerne schließen.
