### ISSUE TITLE
Styling:  Keine Schatten bei Klick bzw. Aktivierung (Menü, Formularfelder etc...)

### ISSUE THREAD

**Issue by tilmansch** [PurposeDevelopment/bnb-frontend#159]
<img width="759" alt="Bildschirmfoto 2020-02-29 um 20 15 01" src="https://user-images.githubusercontent.com/7920981/75613688-e8c4f080-5b30-11ea-9bc8-aeb49580e9a6.png">
<img width="817" alt="Bildschirmfoto 2020-02-29 um 20 19 06" src="https://user-images.githubusercontent.com/7920981/75613689-eb274a80-5b30-11ea-90f1-5ef279fb4b21.png">

**Comment by karlbaumhauer** [comment]
@tilmansch wir brauchen aber eine Lösung für Menschen, die nur die Tastatur nutzen. Es muss einen Rahmen geben, welche für Elemente im Fokus angezeigt wird. Standard ist ein blauer Rahmen und der sieht kacke aus...;-)

**Comment by tilmansch** [comment]
geht: keine  outline als standard und bei tab/aktivierung--> outline? aber schatten weg?
