### ISSUE TITLE
Styling: Schriftgrößen Mobile

### ISSUE THREAD

**Issue by tilmansch** [PurposeDevelopment/bnb-frontend#164]
- [x] Kolumnenzeile kleiner
- [x] H1 kleiner
- [x] H2 kleiner
- [x] Copy kleiner, selbe grösse wie infotext jetzt.
- [x] Infotext bleibt so.

Menü und Footer:
- [x] Menüpunkte kleiner
- [x] Sekundäre infos beim Footer --> wie copy/infotext

**Comment by karlbaumhauer** [comment]
@tilmansch bitte genaue Werte angeben.

**Comment by tilmansch** [comment]
ich komme hier leider nicht in die zahlen rein gerade. aber alles ca 10-20%  kleiner, damit texte schöner laufen, mehr platz ist für lange wörter
