### ISSUE TITLE
Styling: Schriftgrößen Desktop

### ISSUE THREAD

**Issue by tilmansch** [PurposeDevelopment/bnb-frontend#165]
Kolumnenzeile kleiner
- [x] H1 --> passt
- [x] H2 --> passt
- [x] Copy passt
- [x] Infotext kleiner --> wie kolumnenzeile von der schriftgröße her.

Menü und Footer:
- [x] Menüpunkte kleiner
- [x] Sekundäre infos beim Footer --> wie infotext

**Comment by karlbaumhauer** [comment]
@tilmansch bitte genaue Werte angeben. nur noch bei Menüpunkte notwendig.

**Comment by tilmansch** [comment]
@karlbaumhauer ich kann es leider nicht rausbekommen. aber du kannst dich an  dem logo orientieren, versuche es an die schriftgröße  des logos und auch an die unterkante  anzupassen
<img width="684" alt="Bildschirmfoto 2020-03-01 um 15 44 10" src="https://user-images.githubusercontent.com/7920981/75627772-8e30a080-5bd3-11ea-8bfa-8668c3a0b810.png">
.
