### ISSUE TITLE
Styling: Mobile: Ränder links und rechts kleiner machen

### ISSUE THREAD

**Issue by tilmansch** [PurposeDevelopment/bnb-frontend#166]
Mobile wird viel platz Verschenkt an den Rändern.
--> Ränder schmäler machen
![Screenshot_20200229-205803_Chrome](https://user-images.githubusercontent.com/7920981/75616066-75c97300-5b4c-11ea-98b3-c0473983b193.jpg)
![Screenshot_20200229-210723_Chrome](https://user-images.githubusercontent.com/7920981/75616067-7bbf5400-5b4c-11ea-8516-7bc311ed5793.jpg)

**Comment by karlbaumhauer** [comment]
@tilmansch bisher auf mobile 30px, tablet 50px und Desktop wieder 30px. Bitte genaue Wert angeben.

**Comment by tilmansch** [comment]
mobile: 15px
tablet: passt
desktop: passt
