### ISSUE TITLE
Styling Mobile: Grafiken auf komplette Breite ziehen, wie bei Stage (hier auch auf die komplette Breite gehen.)

### ISSUE THREAD

**Issue by tilmansch** [PurposeDevelopment/bnb-frontend#168]
![Screenshot_20200229-205911_Chrome](https://user-images.githubusercontent.com/7920981/75616145-dc9b5c00-5b4d-11ea-9db7-6a921330a3ae.jpg)
![Screenshot_20200229-210151_Chrome](https://user-images.githubusercontent.com/7920981/75616148-ea50e180-5b4d-11ea-8123-64675c4011af.jpg)

**Comment by karlbaumhauer** [comment]
@tilmansch hier bitte ein zwischenwert für Tablet angeben.

**Comment by tilmansch** [comment]
@karlbaumhauer 
dann für so wie es war? ca halbe Content-Breite.
und dann auch diesen wert bei der stage-grafik übernehmen.

**Comment by tilmansch** [comment]
@karlbaumhauer nochmal ich:
bei mir in der simulation  für tablet 1024px habe ich die grafiken  (herausforderung/lösung) trotzdem nebem  dem text. würde für mich so passen
