### ISSUE TITLE
Styling Mobile: Mehr Abstand zwischen Elementen bei dem "How To" auf Startseite

### ISSUE THREAD

**Issue by tilmansch** [PurposeDevelopment/bnb-frontend#169]
zwischen den ei
![Screenshot_20200229-205937_Chrome](https://user-images.githubusercontent.com/7920981/75616370-56cce000-5b50-11ea-8283-ea74a420e0df.jpg)
nzelnen Steps mehr Platz einfügen.

**Comment by karlbaumhauer** [comment]
@tilmansch wird schwer für Dich im Inspector auszuprobieren... kannst Du in etwa sagen wie viel mehr? doppelt so viel wie bisher oder ⅓ mehr...

**Comment by tilmansch** [comment]
doppelt soviel abstand

**Comment by tilmansch** [comment]
jetzt sind auch innerhalb des einzelnen punktes zwischen titel und infotext die abstände größer geworden. bitte die abstände zum nächsten punkt so lassen, und die innerhalb wieder verkleinern.
![Screenshot_20200301-224357_Chrome](https://user-images.githubusercontent.com/7920981/75634450-54c95680-5c0e-11ea-9a7c-1e66e75abe91.jpg)

**Comment by karlbaumhauer** [comment]
@tilmansch das liegt daran, dass wir mehrzeilige Überschriften haben. Wenn ich die wieder zurück setze, ist der Abstand nicht immer gleich sobald die Überschrift umbricht.

**Comment by karlbaumhauer** [comment]
wenn das nicht gewünscht ist, müsstest Du genauer spezifizieren wie der Umbruch auf Mobil auszusehen hat. Ich hab es eben vorhin geändert, da es schrecklich aussah.

**Comment by tilmansch** [comment]
aber bei dem element gibt es doch keine zweizeiligen, oder? kommt das  element sonst noch irgendwo vor bis jetzt?

**Comment by karlbaumhauer** [comment]
wenn du aber auf einem kleinen handy bist schon...

**Comment by tilmansch** [comment]
ah ok doch, habs gesehen. dann erstmal ignorieren. sieht auf dem handy leider doof aus. prio3 ;-)
