### ISSUE TITLE
Content: Zu lange Inhalte für Buttons

### ISSUE THREAD

**Issue by tilmansch** [PurposeDevelopment/bnb-frontend#174]
@AlisaSophie 
<img width="1078" alt="Bildschirmfoto 2020-03-01 um 00 23 31" src="https://user-images.githubusercontent.com/7920981/75616603-423e1700-5b53-11ea-93ed-15409f88e072.png">
![Screenshot_20200301-002638_Chrome](https://user-images.githubusercontent.com/7920981/75616609-6bf73e00-5b53-11ea-9d87-82512da62acb.jpg)

Inhalte lieber in den Text und dann einen griffigen Button-Text.
Das Datum hat hier nichts zu suchen, vor allem wenn der button keinerlei Funktion hat.

**Comment by AlisaSophie** [comment]
statt "werde Teil von BNB" -> "ich bin dabei"

statt "Schlage hier..." --> Button rausnehmen bis zum Start der Kampagne, da er im Moment nicht klickbar ist. Stattdessen in den Text einfügen: "Am 12.03.2020 öffnen wir hier uns Nominierungsformular. Schlage dann deine*n Kandidat*in vor."
