### ISSUE TITLE
Newsletter Adresse Bestätigungsfeld

### ISSUE THREAD

**Issue by AlisaSophie** [PurposeDevelopment/bnb-frontend#175]
Habe mich für den Newsletter angemeldet. Im Bestätigungstext erscheint eine Adresse, Schanzenbachstraße (hier wohne ich, aber die Hausnummer ist falsch?) Wo kommt die her? Haben wir doch noch nie verwendet?

**Comment by karlbaumhauer** [comment]
@AlisaSophie die wird in Mailchimp gepflegt. Die könnt ihr selbst dort ändern.

**Comment by AlisaSophie** [comment]
Aha! Danke!! :) @karlbaumhauer

**Comment by karlbaumhauer** [comment]
wont fix
