### ISSUE TITLE
Kontaktformular verschwunden

### ISSUE THREAD

**Issue by AlisaSophie** [PurposeDevelopment/bnb-frontend#193]
Das Kontaktformular auf der Seite Kontakt, unser Ersatz für das Volunteerformular, ist verschwunden? Hier konnte man sich doch eintragen und hat auch die Möglichkeit, einen Freitext zu schreiben? Ich hatte dafür auch einen anderen Text vorgesehen (gestern erst), damit die Leute mit uns in Kontakt treten können? Jetzt gibt es nur noch das Newsletterfeld.

**Comment by karlbaumhauer** [comment]
@AlisaSophie da haben wir uns dann die ganze Zeit missverstanden. Das Kontaktformular ist leider nicht fertig geworden. Da hakt es noch an technischen Kleinigkeiten. Steht aber auf der ToDo Liste recht weit oben.
