### ISSUE TITLE
several text changes

### ISSUE THREAD

**Issue by AlisaSophie** [PurposeDevelopment/bnb-frontend#194]
- [x] FAQ - wer entscheidet was? Klammer mit (siehe auch Frage 18 unten) bitte rausnehmen.
- [x] Forderungen - unser Selbstverständnis: Zu Beginn des kursiven Absatzes fehlt ein Brand
- [x] Über uns - Forderungen: bitte die Aufzählungszeichen anpassen ("in Bezug auf" rausnehmen):
-Klimakrise - Die größte Herausforderung unserer Zeit.
-Soziale Gerechtigkeit - Ein Fundament für unser Zusammenleben.
-Nachhaltiges Wirtschaften - Eine WIRtschaft, die allen zu Gute kommt.
-Europa - Gestärkt als vereinte und vernetzte Solidargemeinschaft.
- [x] Footer: Bitte das "so erreichst du uns" inkl. Adresse und Mail hier rausnehmen und dafür in Kontakt einfügen. Daniel wünscht sich das, weil es sie Adresse seiner Mutter ist. Dann ist sie nicht mehr ganz so präsent.

**Comment by AlisaSophie** [comment]
Forderungen - unser Selbstverständnis: Zu Beginn des kursiven Absatzes fehlt ein **Brand**

**Comment by AlisaSophie** [comment]
Über uns - Forderungen: bitte die Aufzählungszeichen anpassen ("in Bezug auf" rausnehmen):

- Klimakrise - Die größte Herausforderung unserer Zeit.

- Soziale Gerechtigkeit - Ein Fundament für unser Zusammenleben.

- Nachhaltiges Wirtschaften - Eine WIRtschaft, die allen zu Gute kommt.

- Europa - Gestärkt als vereinte und vernetzte Solidargemeinschaft.

**Comment by AlisaSophie** [comment]
Footer: Bitte das "so erreichst du uns" inkl. Adresse und Mail hier rausnehmen und dafür in Kontakt einfügen. Daniel wünscht sich das, weil es sie Adresse seiner Mutter ist. Dann ist sie nicht mehr ganz so präsent.

**Comment by AlisaSophie** [comment]
- [ ] Startseite - BNB Prinzip: Punkt zwischen "...zu kommen" und "deshalb"

- [ ] Startseite - BNB Prinzip: bitte bei geschafft einen Text ergänzen: „Wir begleiten unsere neuen Parlamentarier*innen auf ihrem Weg durch den deutschen Bundestag“

- [ ] aktiv werden - Überschrift H1: bei Kandidat*innen fehlt ein "d"

- [ ] aktiv werden - Wir brauchen dich: Egal, ob du gerne Menschen zusammenbringst, kreativ bist, einfach für Politik brennst oder Expert*in auf einem **nützlichen** Gebiet bist  -> "nützlichen" bitte streichen

- [ ] Über uns - Forderungen: Politik für die breite Gesellschaft – für dich und Mich! -> "mich" bitte klein schreiben

- [ ] Über uns - Forderungen: Wir fordern, dass Politik wieder für die gemacht wird, für die sie bestimmt ist: Für Dich und mich. -> hier bitte "dich" kleinschreiben

- [ ] FAQ - bitte Vision austauschen (siehe auch "über uns"): 
Wir kämpfen für eine Gesellschaft, in der Menschen gemeinsam und mutig ihre Zukunft gestalten. Für eine Gesellschaft, die alle Menschen einschließt. Wir kämpfen für ein Recht auf Chancengleichheit und individuelle Teilhabe. Für eine Gesellschaft, die das eigene Handeln reflektiert und sich ihrer globalen Bedeutung bewusst ist. Wir kämpfen für eine europäische Gesellschaft, die vielfältige Identitäten schützt und jedem Menschen offen steht. Für eine europäische Politik, die Nachhaltigkeit in allen Bereichen als Handlungsmaxime begreift. Die auf Augenhöhe mit anderen Regionen eine gerechte Welt vorantreibt und stetig neu definiert.

- [ ] FAQ - Wie ist die Bewegung organisiert: Im 1. Satz bitte "vier" statt "fünf" Freunde schreiben

**Comment by AlisaSophie** [comment]
- [ ] Impressum: 1. Angaben gemäß § 5 des Telemediengesetzes - bitte vorübergehend raus und Hamburg rein: "Die Wir für Zukunft eG i. Gr. ist eine sich in der Gründung befindliche Genossenschaft nach den Vorschriften des BGB mit (**vorübergehendem** -> raus) Sitz in Hamburg. Sie ist eingetragen im Vereinsregister des Amtsgerichts Hamburg unter der Nummer VR (Angabe folgt in Kürze)" 

- [ ] FAQ: Wer entscheidet bei euch was? - bitte anpassen: "Die zentralen organisatorischen Entscheidungen fällen wir aktuell gemeinsam im Kernteam, das aus vier Personen besteht. Unsere nicht-gemeinnützigen Aktivitäten organisieren wir genossenschaftlich-demokratisch." 

- [ ] Kontakt: Unter Spendenkonto bitte einfügen: “Unsere gemeinnützige politische Bildungsarbeit, mit der wir Menschen dafür begeistern möchten, sich politisch zu engagieren, betreiben wir über den BNB eV. Diese kannst du mit einer Spende unterstützen. Vielen Dank!”

**Comment by karlbaumhauer** [comment]
@AlisaSophie Änderungen sind auf staging.brandnewbundestag.de zu sehen. Bitte kurz durchschauen und mir ein Go geben. Danach kommen sie auf den Master.

**Comment by AlisaSophie** [comment]
vielen Dank! Alles perfekt, bis auf eine Sache (mein Fehler, da ich es nicht richtig gekennzeichnet habe und sich ein Fehler eingeschlichen hat - sorry!): 

- [ ] Impressum - 1. Angaben gemäß... -> bitte Vereinsregister durch Genossenschaftsregister tauschen und Amtsgericht Hamburg ergänzen
"Die Wir für Zukunft e.G. i.Gr. ist eine sich in Gründung befindliche Genossenschaft nach den Vorschriften des Genossenschaftsgesetzes mit Sitz in Hamburg. Sie ist eingetragen im **Genossenschaftsregister des Amtsgerichts Hamburg** unter der Nummer VR (Angabe folgt in Kürze)."

**Comment by AlisaSophie** [comment]
- [ ] Forderungen - Politische Plattform: Bitte Text austauschen

"Die Welt (und unser Land) steht vor großen Herausforderungen. Wir brauchen Menschen im Bundestag, die die Fragen und Probleme unserer Zeit mutig und zukunftsorientiert als Lautsprecher der Zivilgesellschaft angehen. BNB bietet eine politische Plattform, um diese progressiven Kräfte zu vereinen. Wir wollen endlich eine konsequente Antwort auf die Klimakrise, die eine existenzielle Bedrohung für die Welt darstellt. Wir wollen mehr soziale Gerechtigkeit schaffen und Perspektiven für alle Menschen in unserem Land bieten. Wir wollen einen Umbau unserer Wirtschaft zu einem nachhaltigen System, das nicht auf die Kosten kommender Generationen arbeitet. Wir wollen ein Europa, das eine starke und vernetzte Solidargemeinschaft bildet."

- [ ] Forderungen: Faire Verteilung der Klimakosten: bitte Text austauschen
"Unternehmen und Energiekonzerne dürfen sich nicht weiter der Verantwortung für Folgeschäden von Umweltverschmutzung und CO2-Ausstoß entziehen. Ein gerechter Ausgleich, der die Kosten und Schäden der Umweltzerstörung effektiv einpreist, muss sich flächendeckend nach dem Verursacherprinzip ausrichten. Die Kosten des notwendigen Umbaus unserer Wirtschaft müssen sozial gerecht verteilt werden."
