### ISSUE TITLE
Sozial Media Share Image bereitstellen

### ISSUE THREAD

**Issue by karlbaumhauer** [PurposeDevelopment/bnb-frontend#208]
hier ein paar Infos dazu: 

> Reconciling the guidelines for the image is simple: follow Facebook's recommendation of a minimum dimension of 1200x630 pixels and an aspect ratio of 1.91:1, but adhere to Twitter's file size requirement of less than 1MB.

https://allfacebook.de/fbmarketing/og-tags-optimieren

Vielleicht hat @VickyW987  ja noch Hinweise dafür parat. So wie ich es verstanden habe, dauert es bei Facebook eh 30 Tage bis die das aktualisieren...

**Comment by VickyW987** [comment]
Moin @karlbaumhauer,

das stimmt, der normale Zyklus bei FB sind diese 30 Tage - wenn man selbst nichts aktiv anstößt und FB mitteilt.

Man kann den Prozess aber etwas beschleunigen:
- Wenn man ein neues Bild hinterlegt, sollte das im tag og:image auch unterschiedlich benannt sein, das erkennt FB sofort und ändert das Bild in seiner Vorschau.
- Bei weiteren Änderungen der og tags kann man zusätzlich über den Sharing Debugger von FB prüfen, welche Fehlermeldungen ausgegeben werden und dort auch anstoßen, dass die neuen Infos übernommen werden. https://developers.facebook.com/tools/debug/

Hilft euch das schon weiter?
LG
Vicky

**Comment by karlbaumhauer** [comment]
@VickyW987 danke für die Info. Ich hab leider kein Facebook mehr und muss auch noch kurz warten bis ich mit meiner Emailadresse ein neues Konto erstellen kann (hab mein altes erst vor kurzem gelöscht und werde mir ein "cleanes" Konto für die Arbeit erstellen. Vll kann das ja jemand anderes mal testen (@AlisaSophie, @VickyW987 oder @tilmansch) und mir dann den report schicken.

**Comment by VickyW987** [comment]
Hallo @karlbaumhauer und @AlisaSophie,

ich habe mir das jetzt noch mal auf FB und Twitter angeschaut.
Für Twitter sieht soweit alles gut aus:
![Bildschirmfoto 2020-03-22 um 14 19 21](https://user-images.githubusercontent.com/61582734/77251607-9074a080-6c4f-11ea-8b90-efb9bb565126.png)

Für FB sieht es so aus, als wenn das Bild gerade nur für Desktop funktioniert, so hier:
![Bildschirmfoto 2020-03-22 um 14 19 53](https://user-images.githubusercontent.com/61582734/77251619-a5513400-6c4f-11ea-9769-bc85f6deb891.png)

Bei der mobile Vorschau sieht es so aus:
![Screenshot_20200322-144739](https://user-images.githubusercontent.com/61582734/77251631-bc902180-6c4f-11ea-8a82-4307543ba88c.png)

Wisst ihr ob das jetzt ein neues Problem ist oder ob das vorher schon der Fall war?

Der Report unter https://developers.facebook.com/tools/debug/ sieht gut aus, es wird nur ein Warnhinweis ausgegeben, dass das Merkmal fb:app_id fehlt und den Hinweis kann man ignorieren, wenn man keine App hat, die dort angegeben werden kann. 

VG
Vicky

**Comment by karlbaumhauer** [comment]
@VickyW987 ich hab das Bild nochmal überarbeitet und die genauer Dimensionen von Facebook genutzt. Also genau das Mindestmaß von 1200x630px genommen und damit auch das exakte Seitenverhältnis. Dazu gebe ich nun auch die von FB vorgeschlagenen Größen des Bildes genau an (og:image.width und og:image:height). Mal sehen ob das hilft. Wenn es für dich passt, kannst auch hier das Ticket gerne schließen.

**Comment by VickyW987** [comment]
Jetzt sieht alles gut aus. :)
