### ISSUE TITLE
Nominierung Wahlkreis Bestätigungsmail

### ISSUE THREAD

**Issue by AlisaSophie** [PurposeDevelopment/bnb-frontend#228]
In der Bestätigungsmail fehlt der versprochene Anhang mit den eingegebenen Daten.

Ansonsten funktioniert alles :) Danke!

**Comment by karlbaumhauer** [comment]
Speicher klicken wäre eine gute Idee gewesen...;-) 

sollte jetzt gehen.

**Comment by AlisaSophie** [comment]
was speichern?

**Comment by karlbaumhauer** [comment]
ich hab haken bei Anhang mitsenden zwar gesetzt aber nicht gespeichert...;-) mein Fehler...

**Comment by AlisaSophie** [comment]
achso, haha, ich dachte, ich habe irgendwas nicht gespeichert :D Dann ist ja alles gut, danke!
