### ISSUE TITLE
Neue Deadline Nominierung: 30. Juni 2020

### ISSUE THREAD

**Issue by wirgehenschonmalvor** [PurposeDevelopment/bnb-frontend#243]
@karlbaumhauer  
Bitte aktualisieren mit folgendem Text:

Die Corona Krise hat auch unsere Prozesse ordentlich durcheinander gewirbelt und auf den Kopf gestellt. Deswegen verlängern wir die Frist zur Nominierung der Kandidat*innen bis zum 30. Juni 2020.
Nutze die Chance und nominiere jetzt deine Kandidat*in für die Wahl in 2021 und gemeinsam gestalten wir einen Brand New Bundestag!

**Comment by karlbaumhauer** [comment]
In dem Fall wäre es ein Zusatztext, der gleich auf der Startseite im lila Kasten stehen kann und auf der Seite „Aktiv werden“ muss das Datum geändert werden
