### ISSUE TITLE
Textänderung Button auf Aktiv-Werden-Seite

### ISSUE THREAD

**Issue by wirgehenschonmalvor** [PurposeDevelopment/bnb-frontend#251]
@karlbaumhauer bitte den Text des Buttons "Ich bin dabei!" auf der Seite: https://brandnewbundestag.de/aktiv-werden.html in "Registriere dich hier als Vounteer!" ändern.

**Comment by karlbaumhauer** [comment]
@wirgehenschonmalvor die Texte für Buttons müssen kurz sein, damit auf Mobilgeräten der Button nicht zweizeilig wird. Ich bin dabei war glaub ich fast das Maximum. 
    	
    	

    	
    
  




On Fri, May 29, 2020 at 11:12 AM +0200, "wirgehenschonmalvor" <notifications@github.com> wrote:
















@karlbaumhauer bitte den Text des Buttons "Ich bin dabei!" auf der Seite: https://brandnewbundestag.de/aktiv-werden.html in "Registriere dich hier als Vounteer!" ändern.

**Comment by wirgehenschonmalvor** [comment]
dann "Jetzt registrieren!"
