### ISSUE TITLE
Nachweise im Impressum

### ISSUE THREAD

**Issue by karlbaumhauer** [PurposeDevelopment/bnb-frontend#255]
Folgende Nachweise müssen noch abgenommen bzw. geändert werden (https://brandnewbundestag.de/impressum.html):

- [x] Bilder @wirgehenschonmalvor 
- [x] Design/Gestaltung @tilmansch 
- [x] Programmierung --> @koepferd

**Comment by karlbaumhauer** [comment]
<img width="395" alt="Bildschirmfoto 2020-05-31 um 20 40 12" src="https://user-images.githubusercontent.com/48211526/83360308-950cb200-a380-11ea-893c-cf3b79237331.png">

@tilmansch ich hab die parat.cc Seite verlinkt

**Comment by wirgehenschonmalvor** [comment]
@karlbaumhauer die Postanschrift im Impressum müsste bitte geändert werden in:

Brand New Bundestag
Postfach: 750104
81371 München

**Comment by karlbaumhauer** [comment]
@wirgehenschonmalvor ist erledigt
