### ISSUE TITLE
Home Button

### ISSUE THREAD

**Issue by wirgehenschonmalvor** [PurposeDevelopment/bnb-frontend#267]
@karlbaumhauer 
Beim Home Button komme ich zwar zurück, aber die Jury fehlt ganz. Da wir kein Menüpunkt dafür haben, findet man die Jury nicht mehr - auch nirgends wo anders leider

**Comment by karlbaumhauer** [comment]
@wirgehenschonmalvor bitte nochmal testen. Hab eben ein neuen Release rausgeschickt.
