### ISSUE TITLE
Twitter Buttons

### ISSUE THREAD

**Issue by wirgehenschonmalvor** [PurposeDevelopment/bnb-frontend#268]
@karlbaumhauer 
ich lande auch nach leeren meiner Cookies und dem Cache immer noch auf dem falschen Twitter Account wenn ich auf die Vöglechen klicke. Richtiger Account: @BNBundestag

**Comment by karlbaumhauer** [comment]
@wirgehenschonmalvor bitte nochmal testen. Hab eben ein neuen Release rausgeschickt.
