### ISSUE TITLE
Transparenz Seite ready for Go-Live

### ISSUE THREAD

**Issue by AlisaSophie** [PurposeDevelopment/bnb-frontend#274]
Hi Karl, wir haben nun alle fehlenden Unterlagen für die Transparenzseite zusammen. Ich habe sie im Ordner abgelegt und auch im Dokument darauf hingewiesen und ergänzt: https://drive.google.com/drive/u/0/folders/1OTIrnMTpltGdtTLhTj6kN62Z43sH-dkD. Es wäre super, wenn du sie möglichst bald hochladen könntest. Herzlichen Dank! Liebe Grüße!

**Comment by karlbaumhauer** [comment]
@AlisaSophie aus irgendeinem Grund geht gerade der Staging Server nicht. Daher hier als PDF die Seite. Bitte nochmal prüfen und direkt Korrektur lesen lassen. Ein nachträgliches Korrigieren ist für mich immer extra Aufwand, den ich gerne umgehen möchte.

[Brand New Bundestag - Transparenzseite - 2560x1440.pdf](https://github.com/PurposeDevelopment/bnb-frontend/files/4820560/Brand.New.Bundestag.-.Transparenzseite.-.2560x1440.pdf)


@wirgehenschonmalvor FYI

**Comment by AlisaSophie** [comment]
Lieber Karl,
vielen Dank! wir haben noch ein paar kleiner Änderungsbitten im PDF gemacht und freuen uns, wenn die Seite dann bald live geht, da immer mehr Fragen kommen, wie wir uns finanzieren. Danke dir!
[Brand.New.Bundestag.-.Transparenzseite.-.2560x1440.pdf](https://github.com/PurposeDevelopment/bnb-frontend/files/4836449/Brand.New.Bundestag.-.Transparenzseite.-.2560x1440.pdf)

**Comment by karlbaumhauer** [comment]
@AlisaSophie & @wirgehenschonmalvor Seite ist live
