### ISSUE TITLE
google search engine file

### ISSUE THREAD

**Issue by karlbaumhauer** [PurposeDevelopment/bnb-frontend#277]
@VickyW987 du hattest mir mal vor einiger Zeit eine Google Datei geschickt, welche ich ins Hauptverzeichnis legen sollte. 
Leider muss ich auf Grund verschiedener Probleme den Hauptpfad neu erstellen. Nun finde ich die Datei leider nicht mehr. Damit das nicht nochmal passiert, würde ich sie gerne ins Repo legen. 

Kannst du sie hier nochmal hochladen oder sie mir auch gern einfach per Mail schicken...?

danke und lg
karl

**Comment by VickyW987** [comment]
Hallo @karlbaumhauer,

kein Problem, hier noch einmal die HTML Datei.

VG
Vicky

[googlee18c713b2c97312e.html.zip](https://github.com/PurposeDevelopment/bnb-frontend/files/4842104/googlee18c713b2c97312e.html.zip)

**Comment by karlbaumhauer** [comment]
@VickyW987 super danke dir.
