### ISSUE TITLE
Fehler im Nominierungsformular

### ISSUE THREAD

**Issue by wirgehenschonmalvor** [PurposeDevelopment/bnb-frontend#278]
@karlbaumhauer 

es scheint einen Fehler im Nominierungsformular zu geben. Habe dir die Mail mal weitergeleitet - das ist ausgerechnet die Frau von der Schöpflin Stiftung, die uns eventuell viel Geld geben wollen - kannst du das schnell fixen?

Sie schrieb: 

Liebes BNB Team,

habe gerade mühevoll das Formular ausgefüllt und nun bekomme ich die Fehlermeldung siehe Screenshot anbei. Ich habe das Captcha geklickt und auch ein grünes Häkchen. Könnt Ihr helfen? Ich kopiere meine Antworten derweil in ein Word Dokument und kann sie morgen nochmal einfügen. 

Danke und viele Grüße
Dorothee

<img width="938" alt="Bildschirmfoto 2020-06-24 um 00 51 25" src="https://user-images.githubusercontent.com/65617536/85537725-81b5d500-b614-11ea-8240-e0f9fff1957a.png">

**Comment by karlbaumhauer** [comment]
@wirgehenschonmalvor ich konnte den Fehler nicht reproduzieren... ich hab auch nochmal eine TestNominierung gemacht und die ist super durchgegangen. 

Kannst du den Fehler bei dir nachvollziehen/reproduzieren?

**Comment by wirgehenschonmalvor** [comment]
ich konnte auch jemandne nominieren, problemlos...
Am Ende hat die Userin die Roboter-Aufgabe einfach nicht hingekriegt, dont know

**Comment by karlbaumhauer** [comment]
@wirgehenschonmalvor 
OK. Dann bitte das Ticket schließen.
