### ISSUE TITLE
Ende Nominierungsphase!

### ISSUE THREAD

**Issue by wirgehenschonmalvor** [PurposeDevelopment/bnb-frontend#280]
@karlbaumhauer Lieber Karl, morgen Nacht um 24:00 Uhr endet unsere Nominierungsphase. Könntest du das Formular offline nehmen und an dessen Stelle folgenden Text setzen? Ich fände es gut wenn das Formular noch ein paar Stunden Kulanzzeit nach Mitternacht bekommt, aber in den frühen Mittwoch-Morgenstunden sollte es dann offline gehen... 

Hier der Text. Das Iconset "Kandidatinnen" kann gerne bleiben und nur die Headline und Text links daneben austauschen und natürlich das Formular rausnehmen.

Headline: "Danke für eure Nominierungen!"
Die Nominierungsphase ist vorüber und wir bedanken uns ganz herzlich bei allen Menschen, die so viele spannende und vielversprechende Nominierungen eingereicht, und somit ein großen und wichtigen Schritt, hin zu unserem Brand New Bundestag, gemacht haben!
Falls es noch Fragen oder Probleme mit einer Nominierung gegeben hat, die ihr noch rechtzeitig abgeben wolltet, schreibt uns an einfach eine Mail an team@brandnewbundestag.de und wir finden eine Lösung!

**Comment by karlbaumhauer** [comment]
@wirgehenschonmalvor Das Formular wird Mittwoch früh automatisch deaktiviert und es kommt dann ein kurzer Hinweis. 

Das rausnehmen des gesamten Formulars muss ich dann demnächst machen.

**Comment by wirgehenschonmalvor** [comment]
Ok danke. Was wäre der kurze Hinweis? Wäre es möglich meinen Text zu nehmen, den ich geschrieben habe?

**Comment by karlbaumhauer** [comment]
Ne. Ist eher ein Einzeiler. Steht dann "Danke für eure Nominierungen! Die Frist für Nominierungen ist leider abgelaufen.“

Ich versuche es aber asap zu ändern und deinen Text reinzupacken.

lg
Karl

**Comment by karlbaumhauer** [comment]
Teaser auf der Startseite wurde mit dem Text oben ersetzt (damit nochmal ein Danke/erinnerung an die Nominierung auf der Startseite ist), Hinweis inkl. CTA für Nominierung der Kandidatinnen und Wahlkreise wurde von der aktiv-werden Seite genommen und falls jemand zufällig direkt auf die Nominierungsseite (https://www.brandnewbundestag.de/nominierung.html) ist dort eben auch der obige Text eingetragen und das Formular gelöscht.
