### ISSUE TITLE
Logo in mobile Menü

### ISSUE THREAD

**Issue by karlbaumhauer** [PurposeDevelopment/bnb-frontend#47]
auf kleineren Mobilgeräten überdeckt das geöffnete Menü das Logo. Soll das Logo dann auch in das Menü integriert werden?

sobald ein Display 320px Breite überschreitet, wird das originale Logo allerdings sichtbar.

**Comment by karlbaumhauer** [comment]
<img width="324" alt="Bildschirmfoto 2020-02-16 um 14 03 11" src="https://user-images.githubusercontent.com/48211526/74605132-53a01180-50c5-11ea-963f-d04d5b338ca1.png">
<img width="320" alt="Bildschirmfoto 2020-02-16 um 14 03 20" src="https://user-images.githubusercontent.com/48211526/74605133-56026b80-50c5-11ea-88c9-13b9daad4d95.png">
<img width="424" alt="Bildschirmfoto 2020-02-16 um 14 03 41" src="https://user-images.githubusercontent.com/48211526/74605134-5864c580-50c5-11ea-8e2b-5aa7dc6f4f00.png">

**Comment by karlbaumhauer** [comment]
@tilmansch FYI

**Comment by tilmansch** [comment]
@karlbaumhauer ja bitte gerne das Logo im mobilen Menü anuzeigen.
