### ISSUE TITLE
Kontakt Funktionalität erweitern

### ISSUE THREAD

**Issue by karlbaumhauer** [PurposeDevelopment/bnb-frontend#53]
Bisher ist nur das Frontend erstellt. Versand Funktionalität muss noch integriert werden.

- [ ] staging link aus Dankesseite entfernen!!!
- [x] Validierungsfehler bei Captcha und Checkbox mit Support klären
- [x] Lizenz bestellen

**Comment by tilmansch** [comment]
Styling: passt so. Bitte das Newsletter Formular daran anpassen von den Formularfeldgrößen. Wäre schön wenn alle einheitlich sind am ende (gleiche Höhen, gleiche Abstände...)

**Comment by AlisaSophie** [comment]
könnte das Feld, indem man nach abschicken aufgefordert wird, eine Aufgabe zu lösen, um zu zeigen, dass man kein Bot ist, auch auf deutsch erscheinen? Müssen ja immer damit rechnen, dass jemand kein Englisch kann

**Comment by karlbaumhauer** [comment]
> könnte das Feld, indem man nach abschicken aufgefordert wird, eine Aufgabe zu lösen, um zu zeigen, dass man kein Bot ist, auch auf deutsch erscheinen? Müssen ja immer damit rechnen, dass jemand kein Englisch kann

@AlisaSophie ich trau mich gerade noch nicht direkt das Formular an den Support zu schicken um danach zu fragen. Das ist eine Bestätigungsseite von JotForm und ich hab ja auf unserem das Branding entfernt und bin mir nicht so sicher ob das ok ist. Wenn wir eine Lizenz haben, kümmere ich mich darum. Ich erstelle ein neues Ticket dafür.

**Comment by karlbaumhauer** [comment]
@tilmansch @AlisaSophie 
alle Änderungen sind soweit eingearbeitet. Bitte nochmal testen.

**Comment by AlisaSophie** [comment]
vielen Dank für das schöne Bestätigungsfeld! Finde ich super! In der Mail werden die Infos zweimal angezeigt. Einmal oben nicht so schön und unten schön gelayoutet. Lässt sich das obere entfernen? Rest passt für mich. Danke

**Comment by karlbaumhauer** [comment]
@AlisaSophie ich hab die Email und das PDF nochmal angepasst. Könnt ihr aber auch selbst, da das in dem JotForm Account erstellt wird...;-) ich Zeige Dir mal bei Gelegenheit wie das geht.

Der Rest ist soweit fertig. Ich hab nur noch das Problem, dass die Checkbox für die Datenschutzbestimmungen zwar ausgefüllt werden muss aber wenn das nicht der Fall ist, die User auf eine Validierungsseite von JotForm geleitet werden und dann das Formular leer ist. Ich kläre das noch mit dem Support. Gibt es denn schon News zur Lizenz?

**Comment by karlbaumhauer** [comment]
wie in #204 erwähnt: 
hab einen neuen versuch gestartet und der war deutlich besser. Hab nun das Formular auf eine andere Art eingearbeitet und hab hier viel mehr Möglichkeiten. Nun ist auch das CAPTCHA und die Validieren auf der Seite eingebunden.
gerne testen (http://staging.brandnewbundestag.de/kontakt.html) und Feedback geben.

**Comment by AlisaSophie** [comment]
Sieht schön aus, danke :) Mein Feedback:

- [ ] Muss das Feld mit "Vorwahl" da sein oder könnte man die auch einfach in der Telefonnummer angeben? Fände ich schöner. 

- [ ] Der Button "Formular leeren" erschließt sich mir auch noch nicht so ganz. Brauchen wir den unbedingt? Hätte Sorge, dass Menschen was schreiben und dann versehentlich da drauf klicken, anstatt auf Senden und dann alles weg ist. 

- [ ] Außerdem fände ich es gut, wenn auf dieser Seite dann unten nicht noch zusätzlich das Formular zum Newsletter ist. Danke!

**Comment by AlisaSophie** [comment]
Beim Testen hat auch alles funktioniert, super!!

**Comment by karlbaumhauer** [comment]
@AlisaSophie Telefonnummer ohne Vorwahl ist auf den ersten Blick gerade zu viel Aufwand. Das Feld gibt es nur so und ich müsste die Alternative zusammenbasteln. Hab da aber gerade keine Zeit für. 

Die anderen beiden Punkte hab ich angepasst. gehen dann später noch online.
